# Generated by Django 4.0.1 on 2022-06-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='events',
            new_name='event',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.CharField(default='', max_length=500),
        ),
    ]
